# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "imagick"

    controller:
        redirect_response_code: 302
    twig:
        mode: 'lazy'

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"
                bundle_resources:
                    enabled: true

    filter_sets:
        my_thumb_small:
            quality: 75
            filters:
                thumbnail:
                    size: [ 180, 90 ]
                    position : center
                    mode: inset
                    allow_upscale: true

        my_thumb:
            quality: 95
            filters:
                thumbnail:
                    size: [ 240, 180 ]
                    position: center
                    mode: inset
                    allow_upscale: true
